# Generated by Django 2.2 on 2021-09-10 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20210910_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
