# Generated by Django 2.2 on 2021-09-10 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20210910_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
